sudo: required
services:
  - docker

before_install:
  - docker build -t woddenlock/docker-react -f Dockerfile.dev .

scripts:
  - docker run --name woddenlock/docker-react npm run test -- -- coverage