version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3333:3000" 
    volumes:
      - /app/node_modules
      - .:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true